name: approle
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  draggable_home: ^1.0.3
  firebase_auth: 3.3.18
  firebase_core: 1.17.0
  firebase_core_platform_interface: 4.4.0
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.1
  get: 4.6.3
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  pinput: ^2.2.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
