name: approle
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  draggable_home: ^1.0.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^4.8.0
  flutter_animated_button: ^2.0.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  material_dialogs: ^1.1.3
  pinput: ^2.2.12
  firebase_storage: ^11.2.3
  image_picker: ^0.8.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

