// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-UKQaIJST8kwuScXKIgxFBz7nQP2lSo',
    appId: '1:96784781082:web:6d9bd887401b015b0a66a3',
    messagingSenderId: '96784781082',
    projectId: 'project-database-63eea',
    authDomain: 'project-database-63eea.firebaseapp.com',
    databaseURL: 'https://project-database-63eea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-database-63eea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq18gQkpFPiAMcgYL8uiQ03ADZZLd67nk',
    appId: '1:96784781082:android:d45fdd24fd2fa41e0a66a3',
    messagingSenderId: '96784781082',
    projectId: 'project-database-63eea',
    databaseURL: 'https://project-database-63eea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-database-63eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoccRCqk0Kz_RpkGLMCR7MZ_Fb8XVczcs',
    appId: '1:96784781082:ios:55ef7cfe41437c3b0a66a3',
    messagingSenderId: '96784781082',
    projectId: 'project-database-63eea',
    databaseURL: 'https://project-database-63eea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-database-63eea.appspot.com',
    androidClientId: '96784781082-98bru8i75to0k7efbbugmndigka4dfuc.apps.googleusercontent.com',
    iosClientId: '96784781082-j90t6hc2nvdla8g5g2ranrivnm5ma4k2.apps.googleusercontent.com',
    iosBundleId: 'com.byaxel.approle',
  );
}
